name: Executar Script Python

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar código
        uses: actions/checkout@v3

#      - name: Configurar Python
#        uses: actions/setup-python@v4
#       with:
#         python-version: '3.8'
          
      - name: Executar script
        run: |
          echo "Executando o script PS2ER..."
          pip install matplotlib
          pip install scipy
          pip install scikit-learn
          python3 PS2ER_repo.py
